email: <override me>
privateKeySecretRef: letsencryptstaging
ingress:
  class: nginx
region: eu-central-1
route53:
  region: eu-central-1
  accessKeyID: <override me>
  hostedZoneID: ""
  secretAccessKeySecretRef:
    name: staging-route53-credentials-secret
    key: secret-access-key